### ISSUE TITLE
Support Carthage

### ISSUE THREAD

**Issue by schickling** [artman/HexColor#2]
Please make this package conform to Carthage

**Comment by artman** [comment]
Fixed.

**Comment by schickling** [comment]
Great!

**Comment by schickling** [comment]
Edit: It doesn't seem to be fixed at this point. You need to make your build scheme public to make this work!

**Comment by artman** [comment]
Sorry, missed that one. Now published schemes.

**Comment by schickling** [comment]
Thanks man!
